usuarios2/panel/urls.py
from django.urls import path
from panel import views

app_name="panel"

urlpatterns = [
    path('', views.home, name="home"),
    path('list/', views.list, name="list"),
    path('edit/<int:pk>/', views.edit, name="edit"),
    path('delete/<int:pk>/', views.delete, name="delete")
]

usuarios2/usuarios2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panel.urls'))
]

usuarios2/panel/models.py
from django.db import models

# Create your models here.
class usuarios2(models.Model):
    nombre=models.CharField(null=False, blank=False, max_length=25)
    apellido=models.CharField(null=False, blank=False, max_length=25)
    email=models.CharField(null=False, blank=False, max_length=25)

usuarios2/panel/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from panel.models import usuarios2

# Create your views here.
#INSERT SQL
def home(request):
    if request.POST:
        usuario=usuarios2(
            nombre=request.POST['nombre'],
            apellido=request.POST['apellido'],
            mail=request.POST['mail']
        )
        usuario.save()
    return render(request, 'panel/home.html', locals())
#SELECT
def list(request):
    usuario=usuarios2.objects.all()
    return render(request, 'panel/list.html', locals())
#UPDATE
def edit(request, pk):
    usuario=usuarios2.objects.filter(pk=pk).first()
    if request.POST:
        usuario.nombre=request.POST['nombre']
        usuario.apellido=request.POST['apellido']
        usuario.email=request.POST['email']
        usuario.save()
    return render(request, 'panel/home.html', locals())
#DELETE
def delete(request, pk):
    usuario=usuarios2.objects.get(pk=pk)
    usuario.delete()
    return redirect(reverse('panel:list'))
    

    

usuarios2/panel/templates/panel/home.html
<html>
    <h1>Ingresar un Docente</h1>
    <form action="." method="POST">
        {% csrf_token %}
        <div>
            <label>
                Nombre Docente:
            </label>
            <input type="text" name="nombre" {%if usu%} value="{{usu.nombre}}" {% endif%} required>
        </div>
        <div>
            <label>
                Apellido Docente:
            </label>
            <input type="text" name="apellido" {%if usu%} value="{{usu.apellido}}" {% endif%} required>
        </div>
        <div>
            <label>cd
                Email Docente:
            </label>
            <input type="email" name="email" {%if usu%} value="{{usu.email}}" {% endif%} required>
        </div>
        <div>
            <button type="submit">Enviar</button>
        </div>
    </form>

</html>

usuarios2/panel/templates/panel/list.html
<h1> Listado de Usuarios</h1>
<ul>
    {% for usu in usuario %}
    <li>
        {{usu.nombre}} - {{usu.apellido}} - {{usu.email}}-<a href="{% url 'panel:delete' usu.pk}"></a>-<a href="{% url 'panel:delete' usu.pk}"></a>
    </li>
    {% endfor %}
</ul>